# Generated by Django 2.1 on 2018-08-15 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('landord_id', models.IntegerField()),
                ('name', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=256)),
                ('postcode', models.IntegerField()),
                ('price', models.IntegerField()),
                ('profile', models.TextField(null=True)),
                ('max_guests', models.IntegerField()),
                ('no_of_beds', models.IntegerField()),
                ('no_of_bedrooms', models.IntegerField()),
                ('no_of_baths', models.IntegerField()),
                ('no_of_parking', models.IntegerField()),
                ('tv', models.BooleanField(default=False)),
                ('kitchen', models.BooleanField(default=False)),
                ('washer', models.BooleanField(default=False)),
                ('fridge', models.BooleanField(default=False)),
                ('conditioner', models.BooleanField(default=False)),
                ('wifi', models.BooleanField(default=False)),
                ('study_room', models.BooleanField(default=False)),
                ('pool', models.BooleanField(default=False)),
                ('house_rule', models.TextField()),
                ('cancellation', models.TextField()),
                ('extra', models.TextField(null=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'house',
            },
        ),
        migrations.CreateModel(
            name='House_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('tenant_id', models.IntegerField()),
                ('house_id', models.IntegerField()),
                ('comment', models.TextField()),
            ],
            options={
                'db_table': 'house_comment',
            },
        ),
        migrations.CreateModel(
            name='Landlord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.ImageField(upload_to=None)),
                ('gender', models.BooleanField(default=False)),
                ('dob', models.DateField()),
                ('profile', models.TextField(null=True)),
                ('activate', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'landlord',
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.ImageField(upload_to=None)),
                ('gender', models.BooleanField(default=False)),
                ('dob', models.DateField()),
                ('profile', models.TextField(null=True)),
                ('activate', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tenant',
            },
        ),
    ]
