# Generated by Django 2.1 on 2018-08-15 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landlord',
            name='photo',
        ),
    ]
