# Generated by Django 2.1 on 2018-08-21 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='landord_id',
            new_name='landlord_id',
        ),
    ]
