# Generated by Django 2.1 on 2018-08-25 13:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house_rate',
            old_name='tenant_id',
            new_name='house_id',
        ),
        migrations.RemoveField(
            model_name='house_comment',
            name='tenant_id',
        ),
        migrations.AddField(
            model_name='landlord',
            name='first_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='landlord',
            name='last_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenant',
            name='first_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenant',
            name='last_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='landlord',
            name='phone',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='phone',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
