# Generated by Django 2.1 on 2018-08-27 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_auto_20180827_0450'),
    ]

    operations = [
    ]
