# Generated by Django 2.1 on 2018-10-12 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0009_auto_20181012_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='no_of_rooms',
            field=models.CharField(choices=[('All', 'All'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='A', max_length=3),
        ),
        migrations.AlterField(
            model_name='post',
            name='rent_type',
            field=models.CharField(choices=[('All', 'All'), ('S', 'Share'), ('W', 'Whole')], default='A', max_length=3),
        ),
    ]
